//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanumanInstitute.OntraportApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HanumanInstitute.OntraportApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OntraportConfig.ApiKey is required..
        /// </summary>
        internal static string ConfigApiKeyRequired {
            get {
                return ResourceManager.GetString("ConfigApiKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OntraportConfig.AppId is required..
        /// </summary>
        internal static string ConfigAppIdRequired {
            get {
                return ResourceManager.GetString("ConfigAppIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not available for this object type..
        /// </summary>
        internal static string InvalidMethodForObjectType {
            get {
                return ResourceManager.GetString("InvalidMethodForObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontraport response data could not be parsed..
        /// </summary>
        internal static string InvalidResponseData {
            get {
                return ResourceManager.GetString("InvalidResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objectType must be Rule, Sequence or SequenceSubscriber..
        /// </summary>
        internal static string ObjectTypeMustBeSequence {
            get {
                return ResourceManager.GetString("ObjectTypeMustBeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server returned an error: ({0}).
        /// </summary>
        internal static string ResponseErrorCode {
            get {
                return ResourceManager.GetString("ResponseErrorCode", resourceCulture);
            }
        }
    }
}
